services:
  gateway-api:
    build:
      context: ./gateway-api
    working_dir: /app
    volumes:
      - ./gateway-api:/app
    ports:
      - "3000:3000"
  product-service:
    build:
      context: ./services/product
    working_dir: /app
    volumes:
      - ./product-service:/app
    ports:
      - "8081:8081"
  order-service:
    build:
      context: ./services/order
    working_dir: /app
    volumes:
      - ./order-service:/app
    ports:
      - "8082:8082"
