services:
  gateway-api:
    build:
      context: ./gateway-api
      target: ${DOCKER_ENV:-dev}
    working_dir: /app
    volumes:
      - ./gateway-api:/app
      - /app/node_modules  
    ports:
      - "3000:3000"
  product-service:
    build:
      context: ./services/product
    ports:
      - "8081:8081"
  order-service:
    build:
      context: ./services/order
    ports:
      - "8082:8082"
